name: Yükle ve Dağıt

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Çek
      - uses: actions/checkout@v3
        with:
          repository: bayyavuz/ci-for-javascript # Diğer repo sahibi ve adı
          token: ${{ secrets.YAVUZ69_TOKEN }}
          path: tf-example
          ref: main # Çekmek istediğiniz dal

      - name: AWS Kimlik Bilgilerini Ayarla
        # uses: actions/checkout@v3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - run: | 
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - name: Dosyayı AWS S3'ye Yükle
      - run: |
          aws s3 cp tf-example/terraform.tf s3://for-github-migration-to-s3/
